# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/iabrutin/Work/Ded/OpticApplication

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/iabrutin/Work/Ded/OpticApplication

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iabrutin/Work/Ded/OpticApplication/CMakeFiles /home/iabrutin/Work/Ded/OpticApplication//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iabrutin/Work/Ded/OpticApplication/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpticApplication

# Build rule for target.
OpticApplication: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpticApplication
.PHONY : OpticApplication

# fast build rule for target.
OpticApplication/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpticApplication.dir/build.make CMakeFiles/OpticApplication.dir/build
.PHONY : OpticApplication/fast

#=============================================================================
# Target rules for targets named GeomLib

# Build rule for target.
GeomLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GeomLib
.PHONY : GeomLib

# fast build rule for target.
GeomLib/fast:
	$(MAKE) $(MAKESILENT) -f libs/GeomLib/CMakeFiles/GeomLib.dir/build.make libs/GeomLib/CMakeFiles/GeomLib.dir/build
.PHONY : GeomLib/fast

#=============================================================================
# Target rules for targets named MyGUI

# Build rule for target.
MyGUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyGUI
.PHONY : MyGUI

# fast build rule for target.
MyGUI/fast:
	$(MAKE) $(MAKESILENT) -f libs/MyGUI/CMakeFiles/MyGUI.dir/build.make libs/MyGUI/CMakeFiles/MyGUI.dir/build
.PHONY : MyGUI/fast

#=============================================================================
# Target rules for targets named RayTracer

# Build rule for target.
RayTracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RayTracer
.PHONY : RayTracer

# fast build rule for target.
RayTracer/fast:
	$(MAKE) $(MAKESILENT) -f libs/RayTracer/CMakeFiles/RayTracer.dir/build.make libs/RayTracer/CMakeFiles/RayTracer.dir/build
.PHONY : RayTracer/fast

#=============================================================================
# Target rules for targets named geometry_module

# Build rule for target.
geometry_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geometry_module
.PHONY : geometry_module

# fast build rule for target.
geometry_module/fast:
	$(MAKE) $(MAKESILENT) -f libs/geometry_module/CMakeFiles/geometry_module.dir/build.make libs/geometry_module/CMakeFiles/geometry_module.dir/build
.PHONY : geometry_module/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpticApplication.dir/build.make CMakeFiles/OpticApplication.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpticApplication.dir/build.make CMakeFiles/OpticApplication.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpticApplication.dir/build.make CMakeFiles/OpticApplication.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GeomLib"
	@echo "... MyGUI"
	@echo "... OpticApplication"
	@echo "... RayTracer"
	@echo "... geometry_module"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

